# -*- coding: utf-8 -*-
"""HTTP controllers for the 3CX server-side CRM integration.

The 3CX System Service executes the CRM template generated by
``connect.settings.threecx_get_crm_template()`` on every external call:
contact lookup at call arrival, one ``ReportCall`` journal POST at call
end, and contact creation requested from 3CX clients. Every request
carries the shared API key (``X-Connect-Api-Key`` or ``Authorization:
Bearer``) compared via ``secrets.compare_digest`` (ADR-015); ledger
writes dispatch under the core webhook user (ADR-026 pattern). See
specs/decisions/034-connect-3cx-crm-template-integration.md.

All routes are ``readonly=False``: Odoo 19 ``auth='none'`` routes are
read-only by default, and even the lookup writes (status stamp, debug
log).
"""
import hashlib
import json
import logging
import secrets
from datetime import datetime, timezone

from markupsafe import escape

from odoo import fields, http
from odoo.http import Response, request

logger = logging.getLogger(__name__)

# 3CX CallType -> (call kind, final channel status). The template has no
# call-id variable, so replays are deduplicated by a deterministic SID.
CALL_TYPE_MAP = {
    'Inbound': ('inbound', 'completed'),
    'Missed': ('inbound', 'no-answer'),
    'Outbound': ('outbound', 'completed'),
    'Notanswered': ('outbound', 'no-answer'),
}


def _clean(value):
    """Normalize a 3CX payload value: unresolved/empty variables arrive
    as '', and .NET renders JSON false as the string 'False'."""
    if not isinstance(value, str):
        value = '' if value is None else str(value)
    value = value.strip()
    return '' if value in ('False', 'false', 'null') else value


def _to_int(value):
    try:
        return int(str(value).strip())
    except (TypeError, ValueError):
        return None


class ThreeCXWebhooksController(http.Controller):

    @staticmethod
    def _check_token():
        settings = request.env['connect.settings'].sudo()
        if not settings.get_param('threecx_enabled'):
            return False
        expected = settings.get_param('threecx_api_key') or ''
        if not expected:
            return False
        supplied = request.httprequest.headers.get('X-Connect-Api-Key', '')
        if not supplied:
            auth = request.httprequest.headers.get('Authorization', '')
            if auth.lower().startswith('bearer '):
                supplied = auth[7:].strip()
        if not supplied:
            return False
        return secrets.compare_digest(supplied, expected)

    @staticmethod
    def _json(payload, status=200):
        return Response(
            json.dumps(payload, default=str),
            status=status,
            content_type='application/json',
        )

    @classmethod
    def _unauthorized(cls):
        return Response(
            json.dumps({'error': 'unauthorized'}),
            status=401,
            content_type='application/json',
            headers=[('WWW-Authenticate', 'Bearer')],
        )

    @staticmethod
    def _read_payload():
        raw = request.httprequest.get_data(as_text=True) or ''
        if not raw:
            return {}
        return json.loads(raw)

    @staticmethod
    def _partner_payload(partner):
        """Contact JSON the CRM template maps to its 3CX outputs."""
        settings = request.env['connect.settings'].sudo()
        base_url = (settings.get_param('api_url')
                    or settings.get_param('web_base_url') or '').rstrip('/')
        return {'contact': {
            'id': partner.id,
            'url': '{}/web#id={}&model=res.partner&view_type=form'.format(
                base_url, partner.id),
            'first_name': '',
            'last_name': partner.name or '',
            'company_name': partner.commercial_company_name or '',
            'entity_type': 'Company' if partner.is_company else 'Person',
            'phone_business': partner.phone or '',
            'phone_mobile': getattr(partner, 'mobile', '') or '',
            'email': partner.email or '',
        }}

    @http.route('/3cx/webhook/lookup',
                type='http', auth='none', methods=['GET'], csrf=False,
                readonly=False)
    def lookup(self, number=None, direction=None, **_):
        """Contact lookup fired by 3CX at call arrival (both directions).

        Returns the matched partner as contact JSON, or {} when there is
        no match (the template Rules then report "no result" to 3CX).
        """
        if not self._check_token():
            return self._unauthorized()
        number = _clean(number)
        if not number:
            return self._json({'error': 'no_number'}, status=400)
        settings = request.env['connect.settings'].sudo()
        settings.set_param('threecx_last_lookup', fields.Datetime.now())
        partner = request.env['res.partner'].sudo().get_partner_by_number(
            number)
        if not partner:
            return self._json({})
        return self._json(self._partner_payload(partner))

    @http.route('/3cx/webhook/report_call',
                type='http', auth='none', methods=['POST'], csrf=False,
                readonly=False)
    def report_call(self, **_):
        """Call journal POSTed by 3CX at call end (external calls only)."""
        if not self._check_token():
            return self._unauthorized()
        try:
            payload = self._read_payload()
        except ValueError:
            return self._json({'error': 'bad_json'}, status=400)
        if not isinstance(payload, dict):
            return self._json({'error': 'bad_payload'}, status=400)
        call_type = _clean(payload.get('call_type'))
        if call_type not in CALL_TYPE_MAP:
            return self._json({'error': 'bad_call_type'}, status=400)
        number = _clean(payload.get('number'))
        if not number:
            return self._json({'error': 'no_number'}, status=400)
        try:
            result = self._process_journal(payload, call_type, number)
        except Exception:
            logger.exception('Error processing 3CX call journal:')
            return self._json({'error': 'processing_error'}, status=500)
        return self._json(result)

    @classmethod
    def _process_journal(cls, payload, call_type, number):
        kind, status = CALL_TYPE_MAP[call_type]
        agent = _clean(payload.get('agent'))
        queue = _clean(payload.get('queue_extension'))
        start_millis = _to_int(payload.get('start_utc_millis'))

        # Deterministic SID: 3CX has no call-id variable in the CRM
        # template, so replays of the same journal dedupe by content.
        sid = '3cx-' + hashlib.sha1('|'.join([
            agent, number, str(start_millis or ''), call_type,
        ]).encode()).hexdigest()[:24]

        duration = cls._journal_duration(payload, status)
        connect_user = request.env['connect.user'].sudo()
        if agent:
            connect_user = connect_user.search(
                [('threecx_exten', '=', agent)], limit=1)

        params = {
            'sid': sid,
            'status': status,
            'duration': duration,
        }
        exten = agent or queue
        if kind == 'inbound':
            params.update({
                'caller': number,
                'called': exten,
                'technical_direction': 'inbound',
            })
            if connect_user:
                params['called_pbx_user_id'] = connect_user.id
        else:
            params.update({
                'caller': exten,
                'called': number,
                'technical_direction': 'outbound-api',
            })
            if connect_user:
                params['caller_pbx_user_id'] = connect_user.id

        webhook_user = request.env.ref('connect.user_connect_webhook')
        Channel = request.env['connect.channel'].with_user(webhook_user.id)
        Call = request.env['connect.call'].with_user(webhook_user.id)

        channel = Channel.process_channel_event(params)
        # EntityId round-trips our own lookup output (the partner id):
        # backfill when number-based matching found nothing.
        if not channel.partner:
            entity_id = _to_int(_clean(payload.get('entity_id')))
            if entity_id:
                partner = request.env['res.partner'].sudo().browse(
                    entity_id).exists()
                if partner:
                    channel.sudo().partner = partner.id
        Call.process_call_event(channel)

        cls._maybe_create_recording(channel, payload, sid, start_millis)

        settings = request.env['connect.settings'].sudo()
        settings.set_param('threecx_last_journal', fields.Datetime.now())
        return {'ok': True, 'sid': sid}

    @staticmethod
    def _journal_duration(payload, status):
        """Talk time in seconds: established→end when both stamps are
        present, else the hh:mm:ss Duration string."""
        if status != 'completed':
            return 0
        established = _to_int(payload.get('established_utc_millis'))
        ended = _to_int(payload.get('end_utc_millis'))
        if established and ended and ended >= established:
            return (ended - established) // 1000
        duration = _clean(payload.get('duration'))
        parts = duration.split(':')
        if len(parts) == 3:
            try:
                return (int(parts[0]) * 3600 + int(parts[1]) * 60
                        + int(float(parts[2])))
            except ValueError:
                pass
        return 0

    @staticmethod
    def _maybe_create_recording(channel, payload, sid, start_millis):
        """Store the 3CX recording reference and AI transcript/summary.

        The recording audio is not downloadable at this tier — media_url
        points into the 3CX web client — so the record is created with
        skip_transcription to keep the core OpenAI cron away from it.
        """
        recording_url = _clean(payload.get('recording_url'))
        transcript = _clean(payload.get('transcription'))
        summary = _clean(payload.get('summary'))
        sentiment = _clean(payload.get('sentiment'))
        if not (recording_url or transcript or summary):
            return
        Recording = request.env['connect.recording']
        if Recording.sudo().search([('call_sid', '=', sid)], limit=1):
            return
        summary_html = False
        parts = [escape(p) for p in (summary,) if p]
        if sentiment:
            parts.append(escape('Sentiment: {}'.format(sentiment)))
        if parts:
            summary_html = '<p>{}</p>'.format('<br/>'.join(
                str(p) for p in parts))
        start_time = False
        if start_millis:
            start_time = datetime.fromtimestamp(
                start_millis / 1000.0, tz=timezone.utc).replace(tzinfo=None)
        webhook_user = request.env.ref('connect.user_connect_webhook')
        Recording.with_user(webhook_user.id).with_context(
            skip_transcription=True).create({
                'call_sid': sid,
                'call': channel.call.id if channel.call else False,
                'channel': channel.id,
                'partner': channel.partner.id if channel.partner else False,
                'status': 'completed',
                'source': '3cx',
                'media_url': recording_url or False,
                'transcript': transcript or False,
                'summary': summary_html,
                'duration': channel.duration,
                'caller_number': channel.caller_number,
                'called_number': channel.called_number,
                'start_time': start_time,
            })
        if channel.call and summary_html and not channel.call.summary:
            channel.call.sudo().summary = summary_html

    @http.route('/3cx/webhook/create_contact',
                type='http', auth='none', methods=['POST'], csrf=False,
                readonly=False)
    def create_contact(self, **_):
        """Contact creation requested from a 3CX client for an unmatched
        caller. Returns the full contact JSON (single scenario — no fetch
        chain needed since we control the response shape)."""
        if not self._check_token():
            return self._unauthorized()
        try:
            payload = self._read_payload()
        except ValueError:
            return self._json({'error': 'bad_json'}, status=400)
        if not isinstance(payload, dict):
            return self._json({'error': 'bad_payload'}, status=400)
        first_name = _clean(payload.get('first_name'))
        last_name = _clean(payload.get('last_name'))
        number = _clean(payload.get('number'))
        email = _clean(payload.get('email'))
        company = _clean(payload.get('company'))
        name = ' '.join(p for p in (first_name, last_name) if p) \
            or company or number or email
        if not name:
            return self._json({'error': 'no_data'}, status=400)
        vals = {
            'name': name,
            'phone': number or False,
            'email': email or False,
        }
        if company and company != name:
            vals['company_name'] = company
        # Partner creation is business data the webhook group has no ACL
        # for: token-gated sudo, blast radius documented in ADR-034.
        try:
            partner = request.env['res.partner'].sudo().create(vals)
        except Exception:
            logger.exception('Error creating partner from 3CX:')
            return self._json({'error': 'processing_error'}, status=500)
        return self._json(self._partner_payload(partner))

    @http.route('/3cx/template',
                type='http', auth='user', methods=['GET'], readonly=True)
    def crm_template(self, **_):
        """Download the generated CRM template (Connect admins only)."""
        if not request.env.user.has_group('connect.group_admin'):
            return Response('Forbidden', status=403)
        try:
            xml = request.env['connect.settings'].threecx_get_crm_template()
        except Exception as e:
            return Response(str(e), status=400)
        return Response(
            xml,
            status=200,
            content_type='application/xml; charset=utf-8',
            headers=[('Content-Disposition',
                      'attachment; filename="odoo_connect_3cx.xml"')],
        )
