[build-system]
requires = ["hatchling", "hatch-odoo"]
build-backend = "hatchling.build"

[project]
name = "connect-addons-ng"
version = "19.0.1.1.0"
dynamic = ["dependencies"]

[tool.hatch.metadata.hooks.odoo-addons-dependencies]
[tool.hatch.build.hooks.odoo-addons-dirs]

[tool.hatch.build.targets.wheel]
only-include = ["connect", "connect_twilio", "connect_freeswitch"]
exclude = ["connect/tests", "connect_twilio/tests", "connect_freeswitch/tests"]

[tool.hatch-odoo]
addons_dirs = ["."]
