# -*- coding: utf-8 -*-
"""Single webhook endpoint for all Bird events.

Bird's Notifications API wraps every event in a
``{"service", "event", "payload"}`` envelope, so one URL is enough — the
controller dispatches on the ``event`` key. Requests are authenticated
with the MessageBird HMAC scheme (``messagebird-signature`` +
``messagebird-request-timestamp`` headers, HMAC-SHA256 over
``"{timestamp}\\n{url}\\n{sha256(body)}"``, key = the subscription
signingKey generated by setup_bird_webhooks()).

Like the other providers, event processing dispatches under the core
webhook user (``connect.user_connect_webhook``). Handlers are idempotent
and the endpoint answers 200 even on processing errors: Bird retries
failed deliveries for up to 8 hours, and replaying a poison-pill payload
would only spam the log. Signature failures answer 401 so Bird keeps
retrying while a key misconfiguration is being fixed.
"""
import base64
import hashlib
import hmac
import json
import logging
import time
from urllib.parse import urlparse, urlunparse

from odoo import http
from odoo.http import Response, request

logger = logging.getLogger(__name__)


class BirdWebhooksController(http.Controller):

    @staticmethod
    def _candidate_urls():
        """URLs the signature may have been computed against. Bird signs
        the public HTTPS URL; behind a reverse proxy the request URL can
        differ in scheme or host, so also try the api_url-based
        reconstruction.
        """
        req = request.httprequest
        urls = {req.url.replace('http:', 'https:', 1)}
        api_url = request.env['connect.settings'].sudo().get_param('api_url')
        if api_url:
            parsed_api = urlparse(api_url)
            parsed_req = urlparse(req.url)
            urls.add(urlunparse((
                parsed_api.scheme or 'https',
                parsed_api.netloc,
                parsed_req.path,
                parsed_req.params,
                parsed_req.query,
                '',
            )))
        return urls

    @staticmethod
    def _verify_signature(raw):
        settings = request.env['connect.settings'].sudo()
        if not settings.get_param('bird_verify_requests'):
            return True
        key = settings.get_param('bird_webhook_signing_key')
        signature = request.httprequest.headers.get('messagebird-signature', '')
        timestamp = request.httprequest.headers.get(
            'messagebird-request-timestamp', '')
        if not (key and signature and timestamp and timestamp.isdigit()):
            logger.error('Bird webhook without signature headers or signing key.')
            return False
        tolerance = int(settings.get_param('bird_signature_tolerance') or 300)
        if abs(time.time() - int(timestamp)) > tolerance:
            logger.error('Bird webhook timestamp outside tolerance.')
            return False
        body_hash = hashlib.sha256(raw).digest()
        for url in BirdWebhooksController._candidate_urls():
            signed = b'\n'.join([
                timestamp.encode(), url.encode(), body_hash])
            expected = base64.b64encode(hmac.new(
                key.encode(), signed, hashlib.sha256).digest()).decode()
            if hmac.compare_digest(expected, signature):
                return True
        logger.error('Bird webhook signature mismatch.')
        return False

    @http.route('/bird/webhook', type='http', auth='public',
                methods=['POST'], csrf=False, readonly=False)
    def bird_webhook(self, **kw):
        raw = request.httprequest.get_data()
        if not self._verify_signature(raw):
            return Response('invalid signature', status=401)
        try:
            data = json.loads(raw)
        except ValueError:
            return Response('bad json', status=400)
        event = data.get('event') or ''
        payload = data.get('payload') or {}
        webhook_user = request.env.ref('connect.user_connect_webhook')
        env = request.env(user=webhook_user.id)
        try:
            if event in ('sms.inbound', 'whatsapp.inbound'):
                if payload.get('direction') == 'outgoing':
                    # Some subscriptions replay outgoing messages on the
                    # inbound feed; treat them as status updates.
                    env['connect.message'].update_bird_status(payload, event)
                else:
                    env['connect.message'].receive_bird(payload, event)
            elif event in ('sms.outbound', 'whatsapp.outbound'):
                env['connect.message'].update_bird_status(payload, event)
            elif event in ('voice.inbound', 'voice.outbound'):
                env['connect.call'].on_bird_call_event(payload, event)
            else:
                logger.info('Unhandled Bird webhook event: %s', event)
        except Exception:
            logger.exception('Error processing Bird webhook event %s:', event)
        return Response(
            json.dumps({'ok': True}), status=200,
            content_type='application/json')
