{
    'name': 'Oduist Connect Vonage',
    'version': '19.0.1.0.0',
    'author': 'Oduist',
    'category': 'Phone',
    'summary': 'Vonage integration for Oduist Connect',
    'depends': ['connect'],
    'external_dependencies': {'python': ['vonage']},
    'data': [
        'security/access_rules.xml',
        'views/menu.xml',
        'views/settings_views.xml',
        'views/user_views.xml',
        'views/number_views.xml',
        'views/ncco_views.xml',
        'views/exten_views.xml',
        'views/message_views.xml',
        'data/ir_cron.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'connect_vonage/static/src/icomoon/style.css',
            'connect_vonage/static/src/components/phone/*/*',
            'connect_vonage/static/src/js/main.js',
            'connect_vonage/static/src/js/utils.js',
            'connect_vonage/static/src/widgets/phone_field/*',
            'connect_vonage/static/src/services/actions/*',
            'connect_vonage/static/src/services/active_calls/*',
            'connect_vonage/static/src/services/mail/*',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': False,
    'license': 'Other proprietary',
}
