# -*- coding: utf-8 -*-
import jinja2
import logging
import re
from urllib.parse import urljoin

from odoo import fields, models, api
from odoo.exceptions import ValidationError

from odoo.addons.connect.models.settings import debug
from .settings import format_connect_response
from .texml_response import Dial, VoiceResponse, pretty_xml

logger = logging.getLogger(__name__)


class User(models.Model):
    """Telnyx presence of a PBX user.

    Every field/method contributed here carries the telnyx_ prefix so the
    module co-installs with connect_twilio, which owns the unprefixed
    names on this shared ledger model (ADR-032).

    A user holds up to two Telnyx telephony credentials on the domain's
    credential connection: one for a SIP hardphone and one for the web
    phone (TelnyxRTC). SIP usernames/passwords are generated by Telnyx
    and are readonly here.
    """
    _inherit = 'connect.user'

    originate_provider = fields.Selection(
        selection_add=[('telnyx', 'Telnyx')],
        ondelete={'telnyx': 'set null'},
    )
    message_provider = fields.Selection(
        selection_add=[('telnyx', 'Telnyx')],
        ondelete={'telnyx': 'set null'},
    )
    telnyx_exten = fields.Many2one(
        'connect.telnyx.exten', ondelete='set null', readonly=True,
        string='Telnyx Extension')
    telnyx_exten_number = fields.Char(
        related='telnyx_exten.number', store=True,
        string='Telnyx Extension Number')
    telnyx_outgoing_callerid = fields.Many2one(
        'connect.telnyx.outgoing_callerid', ondelete='set null',
        string='Telnyx Outgoing CallerID')
    telnyx_whatsapp_sender_id = fields.Many2one(
        'connect.telnyx.whatsapp_sender',
        string='Telnyx WhatsApp Sender',
        ondelete='set null',
    )
    telnyx_domain = fields.Many2one(
        'connect.telnyx.domain',
        ondelete='cascade',
        string='Telnyx Domain',
        default=lambda self: self._default_telnyx_domain(),
    )
    telnyx_sip_enabled = fields.Boolean('Telnyx SIP Phone Enabled')
    telnyx_sip_priority = fields.Selection(
        [('1', '1'), ('2', '2')], required=True, default='2',
        string='Telnyx SIP priority',
    )
    # Enabled out of the box only when Telnyx is the sole telephony module;
    # in multi-provider databases the admin enables the Telnyx web phone
    # explicitly per user.
    telnyx_client_enabled = fields.Boolean(
        'Telnyx Web Phone Enabled',
        default=lambda self: self._telnyx_is_only_provider())
    telnyx_client_priority = fields.Selection(
        [('1', '1'), ('2', '2')], required=True, default='1',
        string='Telnyx web client priority',
    )
    telnyx_sip_ring_timeout = fields.Integer(
        required=True, default=30, string='Telnyx SIP ring timeout'
    )
    telnyx_client_ring_timeout = fields.Integer(
        required=True, default=10, string='Telnyx web client ring timeout'
    )
    telnyx_sip_credential_sid = fields.Char('Telnyx SIP Credential ID', readonly=True)
    telnyx_sip_username = fields.Char('Telnyx SIP Username', readonly=True)
    # Unlike Twilio the password is generated by Telnyx and shown to the
    # user: it is needed to provision a SIP hardphone.
    telnyx_sip_password = fields.Char(
        'Telnyx SIP Password', readonly=True,
        groups="connect.group_admin,connect.group_user")
    telnyx_client_credential_sid = fields.Char('Telnyx Client Credential ID', readonly=True)
    telnyx_client_username = fields.Char('Telnyx Client Username', readonly=True)
    telnyx_uri = fields.Char('Telnyx SIP URI', compute='_get_telnyx_uri')

    @api.model
    def _default_telnyx_domain(self):
        # During module installation on a database with existing
        # connect.user rows the new column is initialized before the
        # domain table exists — return no default in that case.
        self.env.cr.execute(
            "SELECT 1 FROM information_schema.tables"
            " WHERE table_name = 'connect_telnyx_domain'")
        if not self.env.cr.fetchone():
            return False
        return self.env['connect.telnyx.domain'].search([], limit=1)

    @api.model
    def _telnyx_is_only_provider(self):
        """True when connect_telnyx is the only telephony module installed."""
        other = self.env['ir.module.module'].sudo().search_count([
            ('name', 'in', ['connect_twilio', 'connect_freeswitch',
                            'connect_asterisk']),
            ('state', '=', 'installed'),
        ])
        return not other

    @api.model
    def _pbx_number_fields(self):
        return super()._pbx_number_fields() + ['telnyx_exten_number']

    @api.constrains('telnyx_sip_enabled', 'telnyx_client_enabled', 'telnyx_domain')
    def _check_telnyx_account(self):
        for rec in self:
            if (rec.telnyx_sip_enabled or rec.telnyx_client_enabled) and not rec.telnyx_domain:
                raise ValidationError(
                    'A Telnyx domain is required to enable the Telnyx SIP '
                    'or web phone for user {}!'.format(rec.name))

    def create_telnyx_extension(self):
        self.ensure_one()
        return self.env['connect.telnyx.exten'].create_extension(
            self, 'connect.user', current_exten=self.telnyx_exten)

    @api.model
    def get_user_by_uri(self, userinfo):
        """Lookup connect.user by SIP URI using the Telnyx credential
        usernames (both hardphone and web client)."""
        if not userinfo:
            return super().get_user_by_uri(userinfo)
        re_call_uri = re.compile(r'^sip:([^@]+)@')
        found_username = re_call_uri.search(userinfo)
        if found_username:
            username = found_username.group(1)
            user = self.env['connect.user'].search([
                '|',
                ('telnyx_sip_username', '=', username),
                ('telnyx_client_username', '=', username)])
            if user:
                debug(self, 'Found user: {} by {}.'.format(user.name, userinfo))
                return user
        return super().get_user_by_uri(userinfo)

    def get_user_by_telnyx_uri(self, userinfo):
        return self.get_user_by_uri(userinfo)

    def _get_telnyx_uri(self):
        for rec in self:
            username = rec.telnyx_sip_username or rec.telnyx_client_username
            rec.telnyx_uri = '{}@sip.telnyx.com'.format(username) if username else ''

    def _create_telnyx_credential(self, channel, client=None):
        """Create one telephony credential (channel: 'sip' or 'client')."""
        self.ensure_one()
        if not self.telnyx_domain or not self.telnyx_domain.sid:
            raise ValidationError(
                'The Telnyx domain is not created yet for user {}!'.format(self.name))
        client = client or self.env['connect.settings'].get_telnyx_client()
        try:
            credential = client.telephony_credentials.create(
                connection_id=self.telnyx_domain.sid,
                name='odoo-{}-{}'.format(channel, self.id),
            )
            data = credential.data
            vals = {
                'telnyx_{}_credential_sid'.format(channel): data.id,
                'telnyx_{}_username'.format(channel): data.sip_username,
            }
            if channel == 'sip':
                vals['telnyx_sip_password'] = data.sip_password
            self.with_context(skip_telnyx_sync=True).write(vals)
            debug(self, 'Created Telnyx {} credential for user {}.'.format(
                channel, self.name))
        except Exception as e:
            raise ValidationError(format_connect_response(e))

    def _ensure_telnyx_credentials(self, client=None):
        """Create the missing credentials for the enabled channels."""
        self.ensure_one()
        client = client or self.env['connect.settings'].get_telnyx_client()
        if self.telnyx_sip_enabled and not self.telnyx_sip_credential_sid:
            self._create_telnyx_credential('sip', client=client)
        if self.telnyx_client_enabled and not self.telnyx_client_credential_sid:
            self._create_telnyx_credential('client', client=client)

    def delete_telnyx_credentials(self):
        self.ensure_one()
        client = self.env['connect.settings'].get_telnyx_client()
        for channel in ['sip', 'client']:
            sid = self['telnyx_{}_credential_sid'.format(channel)]
            if not sid:
                continue
            try:
                client.telephony_credentials.delete(sid)
                debug(self, 'Deleted Telnyx {} credential of user {}.'.format(
                    channel, self.name))
            except Exception as e:
                if 'not found' in str(e).lower() or '404' in str(e):
                    logger.warning(
                        'Telnyx credential %s was not present in Telnyx.', sid)
                else:
                    raise ValidationError(format_connect_response(e))

    @api.model_create_multi
    def create(self, vals_list):
        recs = super().create(vals_list)
        if not self.env.context.get('no_telnyx_create'):
            if self.env['connect.settings'].get_param('telnyx_auto_sync'):
                for rec in recs:
                    if rec.telnyx_sip_enabled or rec.telnyx_client_enabled:
                        rec._ensure_telnyx_credentials()
        return recs

    def write(self, vals):
        res = super().write(vals)
        if self.env.context.get('skip_telnyx_sync'):
            return res
        if not (vals.get('telnyx_sip_enabled') or vals.get('telnyx_client_enabled')):
            return res
        if not self.env['connect.settings'].get_param('telnyx_auto_sync'):
            return res
        for rec in self:
            rec._ensure_telnyx_credentials()
        return res

    def unlink(self):
        for rec in self:
            if self.env["connect.settings"].get_param("telnyx_auto_sync"):
                rec.delete_telnyx_credentials()
        return super().unlink()

    def telnyx_render_client(self, response, request, params):
        caller_name = self._get_telnyx_caller_name(request, params)
        callerId = self._get_telnyx_caller_id(request, params)
        api_url = self.env['connect.settings'].sudo().get_param('api_url')
        record_status_url = urljoin(api_url, 'telnyx/webhook/recordingstatus')
        status_url = urljoin(api_url, 'telnyx/webhook/callstatus')
        dial_action_url = urljoin(
            api_url,
            'telnyx/webhook/connect.user/call_action/{}'.format(self.id),
        )
        dial_client_kwargs = {
            'timeout': self.telnyx_client_ring_timeout,
            'callerId': callerId,
        }
        if params.get('dial_action_url'):
            dial_client_kwargs['action'] = params['dial_action_url']
        else:
            dial_client_kwargs['action'] = dial_action_url
        if self.record_calls:
            dial_client_kwargs.update(
                {
                    'record': 'record-from-answer',
                    'recordingStatusCallback': record_status_url,
                }
            )
        dial_client = Dial(**dial_client_kwargs)
        channel = self.env['connect.channel'].search(
            [('sid', '=', request.get('CallSid'))]
        )
        call = channel.call
        if call and call.partner:
            partner_id = call.partner.id
            if not caller_name:
                caller_name = call.partner.name
        elif channel and channel.caller_user:
            partner_id = channel.caller_user.partner_id.id
            if not caller_name:
                caller_name = channel.caller_user.partner_id.name
        else:
            partner_id = False
        # Custom X- headers travel as SIP URI parameters and surface in
        # the TelnyxRTC notification on the web phone.
        uri = 'sip:{}@sip.telnyx.com?X-CallerName={}&X-Partner={}'.format(
            self.telnyx_client_username, caller_name or '', partner_id or '')
        dial_client.sip(
            uri,
            statusCallbackEvent='initiated answered completed',
            statusCallback=status_url,
        )
        response.append(dial_client)

    def telnyx_render_sip(self, response, request, params):
        callerId = self._get_telnyx_caller_id(request, params)
        api_url = self.env['connect.settings'].sudo().get_param('api_url')
        dial_action_url = urljoin(
            api_url,
            'telnyx/webhook/connect.user/call_action/{}'.format(self.id),
        )
        record_status_url = urljoin(api_url, 'telnyx/webhook/recordingstatus')
        status_url = urljoin(api_url, 'telnyx/webhook/callstatus')
        dial_sip_kwargs = {
            'timeout': self.telnyx_sip_ring_timeout,
            'callerId': callerId,
        }
        if params.get('dial_action_url'):
            dial_sip_kwargs['action'] = params['dial_action_url']
        else:
            dial_sip_kwargs['action'] = dial_action_url
        if self.record_calls:
            dial_sip_kwargs.update(
                {
                    'recordingStatusCallback': record_status_url,
                    'record': 'record-from-answer-dual',
                }
            )
        dial_sip = Dial(**dial_sip_kwargs)
        dial_sip.sip(
            'sip:{}@sip.telnyx.com'.format(self.telnyx_sip_username),
            statusCallbackEvent='initiated answered completed',
            statusCallback=status_url,
        )
        response.append(dial_sip)

    def telnyx_render_voicemail_prompt(self):
        self.ensure_one()
        environment = jinja2.Environment()
        template = environment.from_string(self.voicemail_prompt)
        return template.render({'user': self})

    def get_telnyx_greeting_message(self, response):
        self.ensure_one()
        response.say(
            self.greeting_message,
            language=self.language or 'en-US',
            voice=self.voice or 'Polly.Joanna',
        )

    def get_telnyx_voicemail_prompt(self, response):
        self.ensure_one()
        voicemail_prompt = self.telnyx_render_voicemail_prompt()
        response.say(
            voicemail_prompt,
            language=self.language or 'en-US',
            voice=self.voice or 'Polly.Joanna',
        )

    def telnyx_render_voicemail(self, response, request, params):
        api_url = self.env['connect.settings'].sudo().get_param('api_url')
        voicemail_record_status_url = urljoin(
            api_url, 'telnyx/webhook/vm_recordingstatus')
        self.get_telnyx_voicemail_prompt(response)
        response.record(
            maxLength=120,
            finishOnKey='#',
            playBeep=True,
            recordingStatusCallback=voicemail_record_status_url,
        )

    def telnyx_render(self, request={}, params={}):
        self.ensure_one()
        request = dict(request or {})
        params = dict(params or {})
        channel = self.env['connect.channel'].search(
            [('sid', '=', request.get('CallSid'))], order='id desc'
        )
        call = channel.call
        response = VoiceResponse()
        if call:
            done_callflow_ids = (
                self.env['connect.telnyx.user_callflow_call']
                .sudo()
                .search([('call', '=', call.id)])
                .mapped('callflow')
                .mapped('id')
            )
            if not done_callflow_ids and self.greeting_message:
                self.get_telnyx_greeting_message(response)
            next_call_flow = (
                self.env['connect.telnyx.user_callflow']
                .sudo()
                .search(
                    [
                        ('user', '=', self.id),
                        ('id', 'not in', done_callflow_ids),
                    ],
                    order='prio',
                    limit=1,
                )
            )
            if next_call_flow:
                self.env['connect.telnyx.user_callflow_call'].sudo().create(
                    {
                        'call': call.id,
                        'callflow': next_call_flow.id,
                    }
                )
                getattr(self, next_call_flow.method)(
                    response, request, params
                )
                debug(self, pretty_xml(response.to_xml()))
                return response.to_xml()
            else:
                callflows = (
                    self.env['connect.telnyx.user_callflow_call']
                    .sudo()
                    .search([('call', '=', call.id)])
                )
                callflows.sudo().unlink()
                response.hangup()
                return response.to_xml()
        else:
            all_flows = (
                self.env['connect.telnyx.user_callflow']
                .sudo()
                .search(
                    [('user', '=', self.id)], order='prio'
                )
            )
            for flow in all_flows:
                getattr(self, flow.method)(response, request, params)
            return response.to_xml()

    @api.model
    def get_telnyx_client_token(self):
        try:
            has_user_group = self.env.user.has_group('connect.group_user')
            has_admin_group = self.env.user.has_group('connect.group_admin')
            if not (has_user_group or has_admin_group):
                return {'token': False}
            user = self.search([('user', '=', self.env.user.id)])
            if not user:
                logger.info("User %s not found!", self.env.user.id)
                return {'token': False}
            if not user.telnyx_client_enabled:
                logger.info(
                    "Telnyx client for user %s not enabled!",
                    self.env.user.id,
                )
                return {'token': False}
            if not user.telnyx_client_credential_sid:
                if not user.telnyx_domain:
                    logger.info(
                        "Telnyx domain not set for user %s!", self.env.user.id)
                    return {'token': False}
                user.sudo()._create_telnyx_credential('client')
            client = self.env['connect.settings'].get_telnyx_client()
            token = client.telephony_credentials.create_token(
                user.telnyx_client_credential_sid)
            return {
                'token': token,
                # The web phone dials through this SIP subdomain so Odoo
                # keeps control of the routing (ADR-032).
                'sip_domain': user.telnyx_domain.domain_name,
            }
        except Exception as e:
            logger.exception('Error getting Telnyx JWT:')
            return {'error': str(e)}

    def _get_telnyx_caller_id(self, request, params):
        caller_user = self.env['connect.user'].get_user_by_telnyx_uri(
            request.get('Caller')
        )
        if caller_user:
            callerId = caller_user.telnyx_exten.number or ''
            if not callerId:
                logger.warning(
                    'Exten not set for user %s', caller_user.name
                )
        else:
            callerId = request.get('Caller')
        return callerId

    def _get_telnyx_caller_name(self, request, params):
        caller_user = self.env['connect.user'].get_user_by_telnyx_uri(
            request.get('Caller')
        )
        caller_name = params.get('CallerName', False)
        if caller_user:
            caller_name = caller_user.name
        return caller_name

    @api.constrains('telnyx_sip_enabled', 'telnyx_sip_priority')
    def _manage_telnyx_sip_callflow(self):
        if self.telnyx_sip_enabled:
            self._manage_telnyx_channel_callflow('sip', True)
        else:
            self._manage_telnyx_channel_callflow('sip', False)

    @api.constrains('telnyx_client_enabled', 'telnyx_client_priority')
    def _manage_telnyx_client_callflow(self):
        if self.telnyx_client_enabled:
            self._manage_telnyx_channel_callflow('client', True)
        else:
            self._manage_telnyx_channel_callflow('client', False)

    @api.constrains('voicemail_enabled')
    def _manage_telnyx_voicemail_enabled(self):
        if self.voicemail_enabled:
            if not self.env['connect.telnyx.user_callflow'].search(
                    [('user', '=', self.id),
                     ('callflow_type', '=', 'voicemail')]):
                self.env['connect.telnyx.user_callflow'].create({
                    'user': self.id,
                    'prio': 10,
                    'callflow_type': 'voicemail',
                    'method': 'telnyx_render_voicemail'
                })
        else:
            self.env['connect.telnyx.user_callflow'].search(
                [('user', '=', self.id),
                 ('callflow_type', '=', 'voicemail')]).unlink()

    def _manage_telnyx_channel_callflow(self, channel, enable):
        if enable:
            callflow = self.env['connect.telnyx.user_callflow'].search(
                [
                    ('user', '=', self.id),
                    ('callflow_type', '=', channel),
                ]
            )
            if not callflow:
                self.env['connect.telnyx.user_callflow'].create(
                    {
                        'user': self.id,
                        'callflow_type': channel,
                        'prio': int(
                            getattr(
                                self, 'telnyx_{}_priority'.format(channel)
                            )
                        ),
                        'method': 'telnyx_render_{}'.format(channel),
                    }
                )
            else:
                callflow.prio = getattr(
                    self, 'telnyx_{}_priority'.format(channel)
                )
        else:
            self.env['connect.telnyx.user_callflow'].search(
                [
                    ('user', '=', self.id),
                    ('callflow_type', '=', channel),
                ]
            ).unlink()

    @api.onchange('telnyx_domain')
    def _restrict_telnyx_domain_change(self):
        if (self.telnyx_sip_enabled or self.telnyx_client_enabled) and (
                self.telnyx_sip_credential_sid or self.telnyx_client_credential_sid):
            raise ValidationError(
                'You cannot change the Telnyx domain for an existing account! '
                'Disable the Telnyx phones first!'
            )

    @api.model
    def telnyx_on_call_action(self, record_id, request):
        user = self.browse(record_id)
        call_status = request.get('CallStatus')
        if not call_status:
            call_status = request.get('DialCallStatus')
        if call_status != 'completed':
            dialplan = user.telnyx_render(request)
            return dialplan
        else:
            response = VoiceResponse()
            response.hangup()
            return response.to_xml()
