{
    'name': 'Oduist Connect Bird',
    'version': '19.0.1.0.0',
    'author': 'Oduist',
    'category': 'Phone',
    'summary': 'Bird.com (MessageBird) integration for Oduist Connect',
    'depends': ['connect'],
    'data': [
        'security/access_rules.xml',
        'views/menu.xml',
        'views/settings_views.xml',
        'views/bird_number_views.xml',
        'views/bird_webhook_views.xml',
        'views/message_template_views.xml',
        'views/message_configuration_views.xml',
        'views/message_views.xml',
        'views/user_views.xml',
        'views/call_views.xml',
        'wizard/sms_composer_views.xml',
        'wizard/whatsapp_composer_views.xml',
        'data/ir_cron.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': False,
    'license': 'Other proprietary',
}
