# -*- coding: utf-8 -*-
"""Tests for the outbound CallerID presented on PSTN/gateway calls.

Covers the dialplan generated by ``connect.freeswitch.outgoing_route``:

- the NUMBER is taken from ``connect.user.freeswitch_outgoing_callerid`` when configured;
- the NAME is always blanked so the internal caller's name is never disclosed
  to the outside world (ADR-022), even when a diacritic-laden friendly_name is
  configured in Odoo.
"""
from odoo.tests import tagged
from odoo.tests.common import TransactionCase


@tagged("post_install", "-at_install", "connect_freeswitch", "callerid")
class TestOutgoingRouteCallerId(TransactionCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.Route = cls.env["connect.freeswitch.outgoing_route"].sudo()
        cls.Gateway = cls.env["connect.freeswitch.gateway"].sudo()
        cls.ConnectUser = cls.env["connect.user"].sudo()
        cls.Cid = cls.env["connect.freeswitch.outgoing_callerid"].sudo()

        # Isolate from any seed/demo routes: generate_dialplan scans ALL active
        # routes, so deactivate the others to make matching deterministic.
        cls.Route.search([]).write({"active": False})

        cls.gateway = cls.Gateway.create({"name": "test-trunk", "proxy": "sip.example.com"})
        # National-format destination on purpose: leading 0, not E.164.
        cls.route = cls.Route.create({
            "name": "Test route",
            "pattern": r"^0\d+$",
            "gateway": cls.gateway.id,
        })

        res_user = cls.env["res.users"].create({
            "name": "Celine Rochat",
            "login": "test_cid_celine",
        })
        # friendly_name carries a diacritic to prove the name never leaves Odoo.
        cls.cid = cls.Cid.create({
            "friendly_name": "Céline Rochat",
            "number": "+41215121141",
        })
        cls.user = cls.ConnectUser.create({
            "user": res_user.id,
            "freeswitch_outgoing_callerid": cls.cid.id,
        })

    def _gen(self, destination, connect_user_id=None):
        params = {"Caller-Destination-Number": destination}
        if connect_user_id is not None:
            params["variable_odoo_connect_user_id"] = str(connect_user_id)
        return self.Route.generate_dialplan(params)

    def test_external_call_sets_outgoing_number(self):
        """The outgoing_callerid number is pushed onto the trunk leg."""
        xml = self._gen("0795000992", self.user.id)
        self.assertIn(
            'data="effective_caller_id_number=+41215121141"', xml,
            "outgoing_callerid.number must be set on the outbound leg")

    def test_external_call_blanks_name(self):
        """The caller-id name is blanked; friendly_name never leaks out."""
        xml = self._gen("0795000992", self.user.id)
        self.assertIn(
            'data="effective_caller_id_name="', xml,
            "caller-id name must be explicitly blanked on the outbound leg")
        self.assertNotIn(
            "Céline", xml, "internal friendly_name must not reach the dialplan")
        self.assertNotIn("Rochat", xml)

    def test_no_callerid_and_no_default_leaves_extension(self):
        """No per-user outgoing_callerid and no system default: the number is
        not overridden (the directory-seeded extension stands), but the name is
        still blanked so it is not advertised to the PSTN."""
        self.Cid.search([("is_default", "=", True)]).write({"is_default": False})
        res_user = self.env["res.users"].create({
            "name": "No CID User", "login": "test_cid_none"})
        plain_user = self.ConnectUser.create({"user": res_user.id})

        xml = self._gen("0795000992", plain_user.id)
        self.assertNotIn("effective_caller_id_number=", xml)
        self.assertIn('data="effective_caller_id_name="', xml)

    def test_falls_back_to_system_default_did(self):
        """No per-user CallerID but a system-wide default (is_default) exists:
        the default number is presented on the trunk leg (#96, ADR-027)."""
        # Creating with is_default=True resets any other default via the
        # model's _reset_default constraint, so this is the only default.
        self.Cid.create({
            "friendly_name": "Company Default",
            "number": "+41215120000",
            "is_default": True,
        })
        res_user = self.env["res.users"].create({
            "name": "Default CID User", "login": "test_cid_default"})
        plain_user = self.ConnectUser.create({"user": res_user.id})

        xml = self._gen("0795000992", plain_user.id)
        self.assertIn(
            'data="effective_caller_id_number=+41215120000"', xml,
            "system default DID must be used when the user has no per-user one")
        # The name stays blanked even for the default DID.
        self.assertIn('data="effective_caller_id_name="', xml)

    def test_per_user_callerid_wins_over_default(self):
        """A user's own outgoing_callerid takes precedence over the default."""
        self.Cid.create({
            "friendly_name": "Company Default",
            "number": "+41215120000",
            "is_default": True,
        })
        # self.user already owns cls.cid (+41215121141) as its per-user number.
        xml = self._gen("0795000992", self.user.id)
        self.assertIn(
            'data="effective_caller_id_number=+41215121141"', xml,
            "per-user outgoing_callerid must win over the system default")

    def test_no_matching_route_returns_empty(self):
        """A destination no route matches yields no dialplan (falls through)."""
        # '+...' does not match the '^0\\d+$' pattern.
        self.assertEqual(self._gen("+41215121141", self.user.id), "")
