from . import call
from . import callflow
from . import callflow_choice
from . import channel
from . import debug
from . import endpoint
from . import exten
from . import favorite
from . import mail
from . import message
from . import message_configuration
from . import number
from . import outgoing_callerid
from . import recording
from . import res_partner
from . import res_users
from . import settings
from . import user
from . import user_callflow
