{
    'name': 'Oduist Connect Telnyx',
    'version': '15.0.1.4.4',
    'author': 'Oduist',
    'category': 'Phone',
    'summary': 'Telnyx integration for Oduist Connect',
    'depends': ['connect'],
    'external_dependencies': {
        'python': ['telnyx', 'nacl'],
    },
    'data': [
        'security/access_rules.xml',
        'views/menu.xml',
        'views/settings_views.xml',
        'views/ai_assistant_views.xml',
        'views/texml_views.xml',
        'views/domain_views.xml',
        'views/user_views.xml',
        'views/exten_views.xml',
        'views/callflow_views.xml',
        'views/number_views.xml',
        'views/call_views.xml',
        'views/message_views.xml',
        'views/message_configuration_views.xml',
        'views/outgoing_callerid_views.xml',
        'views/whatsapp_sender_views.xml',
        'views/whatsapp_template_views.xml',
        'views/rcs_agent_views.xml',
        'wizard/sms_composer_views.xml',
        'wizard/whatsapp_composer_views.xml',
        'wizard/rcs_composer_views.xml',
        'wizard/ai_call_wizard_views.xml',
        'data/texml.xml',
        'data/ir_cron.xml',
    ],
    'assets': {
        # Odoo 15: owl templates must go to web.assets_qweb; the mail
        # message-action patches have no 15 counterpart (ADR-062).
        'web.assets_backend': [
            'connect_telnyx/static/src/icomoon/style.css',
            'connect_telnyx/static/src/components/phone/*/*.js',
            'connect_telnyx/static/src/components/phone/*/*.scss',
            'connect_telnyx/static/src/js/main.js',
            'connect_telnyx/static/src/js/utils.js',
            'connect_telnyx/static/src/widgets/phone_field/phone_field.js',
            'connect_telnyx/static/src/services/actions/*.js',
            'connect_telnyx/static/src/widgets/voice_field/voice_field.js',
        ],
        'web.assets_qweb': [
            'connect_telnyx/static/src/components/phone/*/*.xml',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': False,
    'license': 'Other proprietary',
}
